services:
  - type: web
    name: deltaplane-simulator
    env: python
    buildCommand: npm install && npm run build
    startCommand: python server_multiplayer.py
    envVars:
      - key: RENDER
        value: true
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true 