services:
  - type: web
    name: deltaplane-simulator
    env: python
    buildCommand: |
      echo "=== Starting build process ==="
      echo "Current directory: $(pwd)"
      echo "Directory contents before build:"
      ls -la
      echo "Installing Node.js dependencies..."
      npm install
      echo "Building JavaScript bundle..."
      npm run build
      echo "Verifying build output..."
      echo "public directory contents:"
      ls -la public/
      echo "public/js directory contents:"
      ls -la public/js/
      echo "Setting permissions..."
      chmod -R 755 public/
      echo "Installing Python dependencies..."
      pip install -r requirements.txt
      echo "=== Build process completed ==="
    startCommand: python server_multiplayer.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /
    autoDeploy: true 