services:
  - type: web
    name: deltaplane-simulator
    env: python
    buildCommand: |
      echo "=== Starting build process ==="
      echo "Installing Node.js dependencies..."
      npm install
      echo "Building JavaScript bundle..."
      npm run build
      echo "Verifying build output..."
      ls -la public/
      echo "Creating js directory if it doesn't exist..."
      mkdir -p public/js
      echo "Moving bundle files..."
      mv dist/bundle.js* public/js/
      echo "Setting permissions..."
      chmod -R 755 public/
      echo "Final directory structure:"
      ls -R public/
      echo "Installing Python dependencies..."
      pip install -r requirements.txt
      echo "=== Build process completed ==="
    startCommand: python server_multiplayer.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /
    autoDeploy: true 